# =============================================================
# OWNER: AARON
# =============================================================
apiVersion: v1
kind: Secret
metadata:
  name: hyperspectral-secrets
  namespace: hyperspectral
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "CHANGE_ME"
  MINIO_SECRET_KEY: "CHANGE_ME"
  JWT_SECRET_KEY: "CHANGE_ME_USE_LONG_RANDOM_STRING"
  POSTGRES_PASSWORD: "CHANGE_ME"
  SMTP_PASS: "CHANGE_ME"
